/*
 * tls_cipher_suites.cpp
 *
 *  Created on: Jun 6, 2017
 *     License: see LICENSE file
 */

#include <tmos.h>
#include <tls_cipher_suites.h>
#include <hmac.h>
#include <rc4.h>
#include <idea.h>
#include <des.h>
#include <des3.h>
#include <aes.h>
#include <camellia.h>
#include <aria.h>
#include <seed.h>

//Macro for defining a cipher suite
#define TLS_CIPHER_SUITE(identifier, keyExchMethod, cipherAlgo, cipherMode, hashAlgo, prfHashAlgo, \
   macKeyLen, encKeyLen, fixedIvLen, recordIvLen, authTagLen, verifyDataLen) \
   {#identifier, identifier, keyExchMethod, cipherMode, cipherAlgo, hashAlgo, prfHashAlgo, \
   macKeyLen, encKeyLen, fixedIvLen, recordIvLen, authTagLen, verifyDataLen}

//List of supported cipher suites
const tls_chipher_suite_info tls_supported_cipher_suites[] =
{
//TLS_RSA_WITH_RC4_128_MD5 cipher suite RC4-MD5 no shared
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_MD5_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_RC4_128_MD5, TLS_KEY_EXCH_RSA, new_cipher_rc4, CIPHER_MODE_STREAM, new_md5_hash, nullptr, 16, 16, 0, 0, 0, 12),
#endif

//TLS_RSA_WITH_RC4_128_SHA cipher suite RC4-SHA no shared
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_RC4_128_SHA, TLS_KEY_EXCH_RSA, new_cipher_rc4, CIPHER_MODE_STREAM, new_sha1_hash, nullptr, 20, 16, 0, 0, 0, 12),
#endif

//TLS_RSA_WITH_IDEA_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_IDEA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_IDEA_CBC_SHA, TLS_KEY_EXCH_RSA, new_cipher_idea, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 8, 8, 0, 12),
#endif

//TLS_RSA_WITH_DES_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_DES_CBC_SHA, TLS_KEY_EXCH_RSA, new_cipher_des, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 8, 8, 8, 0, 12),
#endif

//TLS_RSA_WITH_3DES_EDE_CBC_SHA cipher suite DES-CBC3-SHA no shared
//#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_RSA_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_RSA, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
//#endif

//TLS_RSA_WITH_AES_128_CBC_SHA cipher suite AES128-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_AES_256_CBC_SHA cipher suite AES256-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_AES_128_CBC_SHA256 cipher suite AES128-SHA256 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_AES_256_CBC_SHA256 cipher suite AES256-SHA256 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_256_CBC_SHA256, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 32, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_AES_128_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_128_CCM, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_RSA_WITH_AES_256_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_256_CCM, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_RSA_WITH_AES_128_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_128_CCM_8, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 8, 12),
#endif

//TLS_RSA_WITH_AES_256_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_256_CCM_8, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 8, 12),
#endif

//TLS_RSA_WITH_AES_128_GCM_SHA256 cipher suite AES128-GCM-SHA256 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_RSA_WITH_AES_256_GCM_SHA384 cipher suite AES256-GCM-SHA384 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_RSA, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_RSA_WITH_CAMELLIA_128_CBC_SHA cipher suite CAMELLIA128-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_CAMELLIA_128_CBC_SHA, TLS_KEY_EXCH_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_CAMELLIA_256_CBC_SHA cipher suite CAMELLIA256-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_CAMELLIA_256_CBC_SHA, TLS_KEY_EXCH_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_RSA_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
//#endif

//TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_RSA_WITH_CAMELLIA_256_CBC_SHA256, TLS_KEY_EXCH_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 32, 16, 16, 0, 12),
//#endif

//TLS_RSA_WITH_CAMELLIA_128_GCM_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_RSA_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_RSA, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
//#endif

//TLS_RSA_WITH_CAMELLIA_256_GCM_SHA384 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_RSA_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_RSA, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
//#endif

//TLS_RSA_WITH_SEED_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_SEED_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_SEED_CBC_SHA, TLS_KEY_EXCH_RSA, new_cipher_seed, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_RSA, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_RSA, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_RSA_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_RSA, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_RSA_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_RSA, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_RSA_WITH_DES_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_DES_CBC_SHA, TLS_KEY_EXCH_DHE_RSA, new_cipher_des, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 8, 8, 8, 0, 12),
#endif

//TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA cipher suite EDH-RSA-DES-CBC3-SHA no shared
//#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_DHE_RSA, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
//#endif

//TLS_DHE_RSA_WITH_AES_128_CBC_SHA cipher suite DHE-RSA-AES128-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_AES_256_CBC_SHA cipher suite DHE-RSA-AES256-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_AES_128_CBC_SHA256 cipher suite DHE-RSA-AES128-SHA256 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 cipher suite DHE-RSA-AES256-SHA256 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_256_CBC_SHA256, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_AES_128_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_128_CCM, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_RSA_WITH_AES_256_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_256_CCM, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_RSA_WITH_AES_128_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_128_CCM_8, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 8, 12),
#endif

//TLS_DHE_RSA_WITH_AES_256_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_256_CCM_8, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 8, 12),
#endif

//TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 cipher suite DHE-RSA-AES128-GCM-SHA256 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 cipher suite DHE-RSA-AES256-GCM-SHA384 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_DHE_RSA, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA cipher suite DHE-RSA-CAMELLIA128-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA, TLS_KEY_EXCH_DHE_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA cipher suite DHE-RSA-CAMELLIA256-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA, TLS_KEY_EXCH_DHE_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_DHE_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
//#endif

//TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_CAMELLIA_256_CBC_SHA256, TLS_KEY_EXCH_DHE_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 32, 16, 16, 0, 12),
//#endif

//TLS_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_DHE_RSA, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
//#endif

//TLS_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_DHE_RSA, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
//#endif

//TLS_DHE_RSA_WITH_SEED_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_SEED_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_SEED_CBC_SHA, TLS_KEY_EXCH_DHE_RSA, new_cipher_seed, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_DHE_RSA, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_DHE_RSA, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_RSA_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_DHE_RSA, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_RSA_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_DHE_RSA, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_RSA_SUPPORT && TLS_CHACHA20_POLY1305_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_DHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_KEY_EXCH_DHE_RSA, nullptr, CIPHER_MODE_CHACHA20_POLY1305, nullptr, new_sha256_hash, 0, 32, 12, 0, 16, 12),
//#endif

//TLS_DHE_DSS_WITH_DES_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_DES_CBC_SHA, TLS_KEY_EXCH_DHE_DSS, new_cipher_des, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 8, 8, 8, 0, 12),
#endif

//TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_DHE_DSS, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
#endif

//TLS_DHE_DSS_WITH_AES_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_DHE_DSS, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_AES_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_DHE_DSS, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_AES_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_DHE_DSS, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_AES_256_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_AES_256_CBC_SHA256, TLS_KEY_EXCH_DHE_DSS, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_AES_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_DHE_DSS, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_DSS_WITH_AES_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_DHE_DSS, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA, TLS_KEY_EXCH_DHE_DSS, new_cipher_camellia, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA, TLS_KEY_EXCH_DHE_DSS, new_cipher_camellia, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_DHE_DSS, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_CAMELLIA_256_CBC_SHA256, TLS_KEY_EXCH_DHE_DSS, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_CAMELLIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_DHE_DSS, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_DSS_WITH_CAMELLIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_DHE_DSS, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_DSS_WITH_SEED_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_SEED_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_SEED_CBC_SHA, TLS_KEY_EXCH_DHE_DSS, new_cipher_seed, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_DHE_DSS, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_DHE_DSS, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_DSS_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_DHE_DSS, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_DSS_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_DSS_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_DSS_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_DHE_DSS, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DH_anon_WITH_RC4_128_MD5 cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DH_ANON_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_MD5_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_RC4_128_MD5, TLS_KEY_EXCH_DH_ANON, new_cipher_rc4, CIPHER_MODE_STREAM, new_md5_hash, nullptr, 16, 16, 0, 0, 0, 12),
#endif

//TLS_DH_anon_WITH_DES_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_DES_CBC_SHA, TLS_KEY_EXCH_DH_ANON, new_cipher_des, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 8, 8, 8, 0, 12),
#endif

//TLS_DH_anon_WITH_3DES_EDE_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_DH_ANON, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
#endif

//TLS_DH_anon_WITH_AES_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_DH_ANON, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_AES_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_DH_ANON, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_AES_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_DH_ANON, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_AES_256_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_AES_256_CBC_SHA256, TLS_KEY_EXCH_DH_ANON, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 32, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_AES_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_DH_ANON, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DH_anon_WITH_AES_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_DH_ANON, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_CAMELLIA_128_CBC_SHA, TLS_KEY_EXCH_DH_ANON, new_cipher_camellia, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_CAMELLIA_256_CBC_SHA, TLS_KEY_EXCH_DH_ANON, new_cipher_camellia, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_CAMELLIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_DH_ANON, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_CAMELLIA_256_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_CAMELLIA_256_CBC_SHA256, TLS_KEY_EXCH_DH_ANON, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 32, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_CAMELLIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_DH_ANON, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DH_anon_WITH_CAMELLIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_DH_ANON, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DH_anon_WITH_SEED_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_SEED_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_SEED_CBC_SHA, TLS_KEY_EXCH_DH_ANON, new_cipher_seed, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_DH_ANON, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_DH_ANON, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_DH_anon_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_DH_ANON, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DH_anon_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DH_ANON_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DH_ANON_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_DH_ANON, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_ECDHE_RSA_WITH_RC4_128_SHA cipher suite ECDHE-RSA-RC4-SHA no shared
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_RSA_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_RC4_128_SHA, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_rc4, CIPHER_MODE_STREAM, new_sha1_hash, nullptr, 20, 16, 0, 0, 0, 12),
#endif

//TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA cipher suite ECDHE-RSA-DES-CBC3-SHA no shared
//#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
//#endif

//TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA cipher suite ECDHE-RSA-AES128-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA cipher suite ECDHE-RSA-AES256-SHA yes
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256 cipher suite ECDHE-RSA-AES128-SHA256 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 cipher suite ECDHE-RSA-AES256-SHA384 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 cipher suite ECDHE-RSA-AES128-GCM-SHA256 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 cipher suite ECDHE-RSA-AES256-GCM-SHA384 yes
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
//#endif

//TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_CAMELLIA_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
//#endif

//TLS_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
//#endif

//TLS_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
//#endif

//TLS_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_ECDHE_RSA, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_RSA_SUPPORT && TLS_CHACHA20_POLY1305_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256, TLS_KEY_EXCH_ECDHE_RSA, nullptr, CIPHER_MODE_CHACHA20_POLY1305, nullptr, new_sha256_hash, 0, 32, 12, 0, 16, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_RC4_128_SHA cipher suite ECDHE-ECDSA-RC4-SHA no shared
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_ECDSA_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_RC4_128_SHA, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_rc4, CIPHER_MODE_STREAM, new_sha1_hash, nullptr, 20, 16, 0, 0, 0, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA cipher suite ECDHE-ECDSA-DES-CBC3-SHA no shared
//#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA cipher suite ECDHE-ECDSA-AES128-SHA no shared
//#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA cipher suite ECDHE-ECDSA-AES256-SHA no shared
//#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256 cipher suite ECDHE-ECDSA-AES128-SHA256 no shared
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384 cipher suite ECDHE-ECDSA-AES256-SHA384 no shared
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_AES_128_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_128_CCM, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_AES_256_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_256_CCM, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_128_CCM_8, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 8, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_256_CCM_8, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 8, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 cipher suite ECDHE-ECDSA-AES128-GCM-SHA256 no shared
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 cipher suite ECDHE-ECDSA-AES256-GCM-SHA384 no shared
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_camellia, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_GCM_SHA384 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
//#endif

//TLS_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_ECDHE_ECDSA, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256 cipher suite ???
//#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_ECDSA_SUPPORT && TLS_CHACHA20_POLY1305_SUPPORT && TLS_SHA256_SUPPORT)
//   TLS_CIPHER_SUITE(TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256, TLS_KEY_EXCH_ECDHE_ECDSA, nullptr, CIPHER_MODE_CHACHA20_POLY1305, nullptr, new_sha256_hash, 0, 32, 12, 0, 16, 12),
//#endif

//TLS_ECDH_anon_WITH_RC4_128_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDH_ANON_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDH_ANON_WITH_RC4_128_SHA, TLS_KEY_EXCH_ECDH_ANON, new_cipher_rc4, CIPHER_MODE_STREAM, new_sha1_hash, nullptr, 20, 16, 0, 0, 0, 12),
#endif

//TLS_ECDH_anon_WITH_3DES_EDE_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDH_ANON_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_ECDH_ANON, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
#endif

//TLS_ECDH_anon_WITH_AES_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDH_ANON_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_ECDH_ANON, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_ECDH_anon_WITH_AES_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDH_ANON_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDH_ANON_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_ECDH_ANON, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_RC4_128_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_PSK_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_RC4_128_SHA, TLS_KEY_EXCH_PSK, new_cipher_rc4, CIPHER_MODE_STREAM, new_sha1_hash, nullptr, 20, 16, 0, 0, 0, 12),
#endif

//TLS_PSK_WITH_3DES_EDE_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_PSK, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
#endif

//TLS_PSK_WITH_AES_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_AES_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_AES_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_AES_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_256_CBC_SHA384, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_AES_128_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_128_CCM, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_PSK_WITH_AES_256_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_256_CCM, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_PSK_WITH_AES_128_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_128_CCM_8, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 8, 12),
#endif

//TLS_PSK_WITH_AES_256_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_256_CCM_8, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 8, 12),
#endif

//TLS_PSK_WITH_AES_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_PSK_WITH_AES_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_PSK, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_PSK, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_CAMELLIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_CAMELLIA_256_CBC_SHA384, TLS_KEY_EXCH_PSK, new_cipher_camellia, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_CAMELLIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_PSK, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_PSK_WITH_CAMELLIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_PSK, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_PSK_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_PSK, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_PSK, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_PSK_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_PSK, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_PSK_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_PSK, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_PSK_WITH_CHACHA20_POLY1305_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_PSK_SUPPORT && TLS_CHACHA20_POLY1305_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_PSK_WITH_CHACHA20_POLY1305_SHA256, TLS_KEY_EXCH_PSK, nullptr, CIPHER_MODE_CHACHA20_POLY1305, nullptr, new_sha256_hash, 0, 32, 12, 0, 16, 12),
#endif

//TLS_RSA_PSK_WITH_RC4_128_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_PSK_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_RC4_128_SHA, TLS_KEY_EXCH_RSA_PSK, new_cipher_rc4, CIPHER_MODE_STREAM, new_sha1_hash, nullptr, 20, 16, 0, 0, 0, 12),
#endif

//TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_RSA_PSK, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
#endif

//TLS_RSA_PSK_WITH_AES_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_RSA_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_PSK_WITH_AES_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_RSA_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_RSA_PSK_WITH_AES_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_RSA_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_PSK_WITH_AES_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_AES_256_CBC_SHA384, TLS_KEY_EXCH_RSA_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_RSA_PSK_WITH_AES_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_RSA_PSK, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_RSA_PSK_WITH_AES_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_RSA_PSK, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_RSA_PSK, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_CAMELLIA_256_CBC_SHA384, TLS_KEY_EXCH_RSA_PSK, new_cipher_camellia, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_RSA_PSK, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_RSA_PSK, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_RSA_PSK_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_RSA_PSK, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_RSA_PSK_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_RSA_PSK, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_RSA_PSK_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_RSA_PSK, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_RSA_PSK_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_RSA_PSK, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_RSA_PSK_SUPPORT && TLS_CHACHA20_POLY1305_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_RSA_PSK_WITH_CHACHA20_POLY1305_SHA256, TLS_KEY_EXCH_RSA_PSK, nullptr, CIPHER_MODE_CHACHA20_POLY1305, nullptr, new_sha256_hash, 0, 32, 12, 0, 16, 12),
#endif

//TLS_DHE_PSK_WITH_RC4_128_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_PSK_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_RC4_128_SHA, TLS_KEY_EXCH_DHE_PSK, new_cipher_rc4, CIPHER_MODE_STREAM, new_sha1_hash, nullptr, 20, 16, 0, 0, 0, 12),
#endif

//TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_DHE_PSK, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
#endif

//TLS_DHE_PSK_WITH_AES_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_PSK_WITH_AES_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_PSK_WITH_AES_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_PSK_WITH_AES_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_256_CBC_SHA384, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_PSK_WITH_AES_128_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_128_CCM, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_PSK_WITH_AES_256_CCM cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_256_CCM, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_PSK_WITH_AES_128_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_128_CCM_8, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 8, 12),
#endif

//TLS_DHE_PSK_WITH_AES_256_CCM_8 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CCM_8_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_256_CCM_8, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_CCM, nullptr, new_sha256_hash, 0, 32, 4, 8, 8, 12),
#endif

//TLS_DHE_PSK_WITH_AES_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_128_GCM_SHA256, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_PSK_WITH_AES_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_AES_256_GCM_SHA384, TLS_KEY_EXCH_DHE_PSK, new_cipher_aes, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_DHE_PSK, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_CAMELLIA_256_CBC_SHA384, TLS_KEY_EXCH_DHE_PSK, new_cipher_camellia, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_CAMELLIA_128_GCM_SHA256, TLS_KEY_EXCH_DHE_PSK, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_CAMELLIA_256_GCM_SHA384, TLS_KEY_EXCH_DHE_PSK, new_cipher_camellia, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_PSK_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_DHE_PSK, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_DHE_PSK_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_DHE_PSK, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_DHE_PSK_WITH_ARIA_128_GCM_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_ARIA_128_GCM_SHA256, TLS_KEY_EXCH_DHE_PSK, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha256_hash, 0, 16, 4, 8, 16, 12),
#endif

//TLS_DHE_PSK_WITH_ARIA_256_GCM_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_GCM_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_ARIA_256_GCM_SHA384, TLS_KEY_EXCH_DHE_PSK, new_cipher_aria, CIPHER_MODE_GCM, nullptr, new_sha384_hash, 0, 32, 4, 8, 16, 12),
#endif

//TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_DHE_PSK_SUPPORT && TLS_CHACHA20_POLY1305_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_DHE_PSK_WITH_CHACHA20_POLY1305_SHA256, TLS_KEY_EXCH_DHE_PSK, nullptr, CIPHER_MODE_CHACHA20_POLY1305, nullptr, new_sha256_hash, 0, 32, 12, 0, 16, 12),
#endif

//TLS_ECDHE_PSK_WITH_RC4_128_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_PSK_SUPPORT && TLS_STREAM_CIPHER_SUPPORT && TLS_RC4_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_RC4_128_SHA, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_rc4, CIPHER_MODE_STREAM, new_sha1_hash, nullptr, 20, 16, 0, 0, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_3DES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_3DES_EDE_CBC_SHA, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_des3, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 24, 8, 8, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 16, 16, 16, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA cipher suite
#if (TLS_MAX_VERSION >= SSL_VERSION_3_0 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA1_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha1_hash, nullptr, 20, 32, 16, 16, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_AES_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_AES_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_AES_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_aes, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_CAMELLIA_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_camellia, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_CAMELLIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_CAMELLIA_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_camellia, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_ARIA_128_CBC_SHA256, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_aria, CIPHER_MODE_CBC, new_sha256_hash, new_sha256_hash, 32, 16, 16, 16, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_PSK_SUPPORT && TLS_CBC_CIPHER_SUPPORT && TLS_ARIA_SUPPORT && TLS_SHA384_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_ARIA_256_CBC_SHA384, TLS_KEY_EXCH_ECDHE_PSK, new_cipher_aria, CIPHER_MODE_CBC, new_sha384_hash, new_sha384_hash, 48, 32, 16, 16, 0, 12),
#endif

//TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256 cipher suite
#if (TLS_MAX_VERSION >= TLS_VERSION_1_2 && TLS_ECDHE_PSK_SUPPORT && TLS_CHACHA20_POLY1305_SUPPORT && TLS_SHA256_SUPPORT)
   TLS_CIPHER_SUITE(TLS_ECDHE_PSK_WITH_CHACHA20_POLY1305_SHA256, TLS_KEY_EXCH_ECDHE_PSK, nullptr, CIPHER_MODE_CHACHA20_POLY1305, nullptr, new_sha256_hash, 0, 32, 12, 0, 16, 12),
#endif
};

#define SUPPORTED_SUITES_NUM (sizeof(tls_supported_cipher_suites)/sizeof(tls_chipher_suite_info))


const tls_chipher_suite_info* get_cipher_suite_info(uint16_t id)
{
	for (uint32_t i = 0; i < SUPPORTED_SUITES_NUM; i++)
	{
		if (tls_supported_cipher_suites[i].suite_identifier == id)
			return &tls_supported_cipher_suites[i];
	}

	//The specified cipher suite is not supported...
	return nullptr;
}

bool is_ecc_cipher_suite(const tls_chipher_suite_info* suite)
{
	//ECC cipher suite?
	if (suite)
	{
		switch (suite->suite_key_exch)
		{
		case TLS_KEY_EXCH_ECDH_RSA:
		case TLS_KEY_EXCH_ECDH_ECDSA:
		case TLS_KEY_EXCH_ECDH_ANON:
		case TLS_KEY_EXCH_ECDHE_RSA:
		case TLS_KEY_EXCH_ECDHE_ECDSA:
		case TLS_KEY_EXCH_ECDHE_PSK:
			return true;
		default:
			break;
		}
	}

	return false;
}

const char* tlsGetCipherSuiteName(uint16_t identifier)
{
	//Parse the list of supported cipher suite
	for (uint32_t i = 0; i < SUPPORTED_SUITES_NUM; i++)
	{
		//The current cipher suite matches the specified identifier?
		if (tls_supported_cipher_suites[i].suite_identifier == identifier)
			return tls_supported_cipher_suites[i].suite_name;
	}

	//Unknown cipher suite...
	return "Unknown";
}

uint32_t tlsGetNumSupportedCipherSuites()
{
	return SUPPORTED_SUITES_NUM;
}

